<script setup lang="ts">
  useHead({
    title: "Create Nuxt App",
    meta: [
      {name: "description", content: "Generated by create nuxt app"},
    ]
  })
</script>
<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>
