<script setup lang="ts">
import "@/assets/styles/reset.css";
import "@/assets/styles/main.css";

useHead({
  title: "Create Nuxt App",
  meta: [
    {name: "description", content: "Generated by create nuxt app"},
  ]
})
</script>
<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>
